logging:
  level:
    root: WARN
    lt.java.exam: DEBUG
    org.springframework.security: WARN

spring:
  jackson:
    deserialization:
      failOnUnknownProperties: false
    mapper:
      accept-case-insensitive-enums: true
  datasource:
    url: jdbc:h2:file:~/project-database
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2
  security:
    user:
      name: admin
      password: password